# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93fb07e30195340d228b5cf2fa041a478c43eb51f5110ad1ba066799991aba2a5f06b2c7a5bc4ea63073f57c81c601e3c690ce8350179f0af358fcb4f326a66f

test:
  secret_key_base: e1eda3fca8d134f0f79c641e5a4c08f4b1416190e5a0ae30b9212df532580b0dee4a2779d3b9a953f324476373832679612bd908e4de6fa0e4deeed2156ab409

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
